#!/usr/bin/php
<?php

// Hook configuration
$basePath = dirname(__FILE__).'/../..';
$phpunitExecutable = $basePath.'/bin/phpunit';
$testsPath = $basePath.'/tests';
$project = 'Web Application';

// Tell the commiter what the hook is doing
echo PHP_EOL;
echo '+ Starting unit tests'.PHP_EOL;

// Execute project unit tests
exec($phpunitExecutable.' '.$testsPath, $output, $returnCode);

// if the build failed, output a summary and fail
if ($returnCode !== 0)
{
    // output the status and abort the commit
    echo '+ Test suite for '.$project.' failed:'.PHP_EOL;
    echo implode("\n", $output);
    echo chr(27).'[0m'.PHP_EOL; // disable colors and add a line break
    echo PHP_EOL;
    exit(1);
}

echo '+ All tests for '.$project.' passed.'.PHP_EOL;
echo PHP_EOL;
exit(0);